version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "5173:80" # Map host 5173 to container 80 (Nginx)
    depends_on:
      - api

  api:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/helpdesk
      - JWT_SECRET=this-is-a-super-secret-key-and-should-be-changed
      - STUB_MODE=true
    depends_on:
      - mongo
    volumes:
      - ./server:/app # Mount local server code for dev changes

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
